port:  5000
markdown: kramdown
name: "Find My Reps"
url: /
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find and contact your local elected representatives"
gems:
  - jekyll-redirect-from
